apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mona-matti
  namespace: argocd

spec:
  project: default

  source:
    repoURL: registry-1.docker.io/anshadin4k
    chart: mona-matti
    targetRevision: "1.0.*"
    helm:
      releaseName: mona-matti

  destination:
    server: https://kubernetes.default.svc
    namespace: production
