apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mona-matti.fullname" . }}-config
  labels:
    {{- include "mona-matti.labels" . | nindent 4 }}
    app: {{ include "mona-matti.name" . }}
data:
  springProfile: {{ .Values.config.springProfile | quote }}
