apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mona-matti.fullname" . }}-secret
  labels:
    {{- include "mona-matti.labels" . | nindent 4 }}
    app: {{ include "mona-matti.name" . }}
type: Opaque
stringData:
  databaseName: {{ .Values.secrets.databaseName | quote }}
  databaseUsername: {{ .Values.secrets.databaseUsername | quote }}
  databasePassword: {{ .Values.secrets.databasePassword | quote }}
  mysqlRootPassword: {{ .Values.secrets.mysqlRootPassword | quote }}
