apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: production

replicas:
  - name: mona-matti
    count: 1

images:
  - name: anshadin4k/mona-matti
    newTag: "48"

