apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mona-matti-mysql-pvc
  labels:
    app: mona-matti-mysql

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi

  storageClassName: standard