apiVersion: v1
kind: Secret

metadata:
  name: mona-matti-secret
  labels:
    app: mona-matti

type: Opaque

stringData:
  databaseName: "mona_matti"
  databaseUsername: "mona_user"
  databasePassword: "mona_password"
  mysqlRootPassword: "rootpassword123"